# Generated by Django 3.2.9 on 2022-02-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('date_brith', models.DateField()),
                ('avatar', models.ImageField(upload_to='author/avatar/', verbose_name='Аватар')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.FileField(upload_to='book/', verbose_name='Книга')),
                ('image', models.ImageField(upload_to='book/image/', verbose_name='Обложка')),
                ('title', models.CharField(max_length=128)),
                ('desc', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('author', models.ManyToManyField(related_name='books_author', to='mainapp.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
            ],
        ),
    ]
